version: '3.8'

services:
  bot-notificator:
    build: .
    container_name: bot-notificator-helper
    restart: unless-stopped
    environment:
      - USE_LOCAL=false
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ADMIN_ID=${ADMIN_ID}
    volumes:
      - ./data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
